Clflags.include_dirs :=
  [ "/opt/opam/4.06.0/lib/base"
  ; "/opt/opam/4.06.0/lib/base/caml"
  ; "/opt/opam/4.06.0/lib/base/shadow_stdlib"
  ; "/opt/opam/4.06.0/lib/bytes"
  ; "/opt/opam/4.06.0/lib/camomile"
  ; "/opt/opam/4.06.0/lib/camomile/default_config"
  ; "/opt/opam/4.06.0/lib/camomile/dyn"
  ; "/opt/opam/4.06.0/lib/camomile/lib_default"
  ; "/opt/opam/4.06.0/lib/camomile/library"
  ; "/opt/opam/4.06.0/lib/fieldslib"
  ; "/opt/opam/4.06.0/lib/findlib"
  ; "/opt/opam/4.06.0/lib/lambda-term"
  ; "/opt/opam/4.06.0/lib/lwt"
  ; "/opt/opam/4.06.0/lib/lwt/unix"
  ; "/opt/opam/4.06.0/lib/lwt_log"
  ; "/opt/opam/4.06.0/lib/lwt_log/core"
  ; "/opt/opam/4.06.0/lib/lwt_react"
  ; "/opt/opam/4.06.0/lib/ocaml/compiler-libs"
  ; "/opt/opam/4.06.0/lib/ocaml/threads"
  ; "/opt/opam/4.06.0/lib/ppx_compare/runtime-lib"
  ; "/opt/opam/4.06.0/lib/ppx_expect/collector"
  ; "/opt/opam/4.06.0/lib/ppx_expect/common"
  ; "/opt/opam/4.06.0/lib/ppx_expect/config"
  ; "/opt/opam/4.06.0/lib/ppx_inline_test/config"
  ; "/opt/opam/4.06.0/lib/ppx_inline_test/runtime-lib"
  ; "/opt/opam/4.06.0/lib/ppx_sexp_conv/runtime-lib"
  ; "/opt/opam/4.06.0/lib/react"
  ; "/opt/opam/4.06.0/lib/result"
  ; "/opt/opam/4.06.0/lib/sexplib0"
  ; "/opt/opam/4.06.0/lib/utop"
  ; "/opt/opam/4.06.0/lib/zed"
  ; "/home/ymehidi/2SN/Traduction de Language/tdl_tam/_build/default/.rat.objs"
  ];

UTop_main.main ();
